# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5dcc9cc4b770ebc23c93b03b80e0ca3d"
name = "Swatch Box"
application_url = "https://swatchbox.91.239.208.85.sslip.io"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[app_proxy]
url = "https://swatchbox.91.239.208.85.sslip.io/proxy"
subpath = "swatchbox"
prefix = "apps"

[auth]
redirect_urls = [
  "https://swatchbox.91.239.208.85.sslip.io/auth/callback",
  "https://swatchbox.91.239.208.85.sslip.io/auth/shopify/callback",
  "https://swatchbox.91.239.208.85.sslip.io/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
